#!/usr/bin/env bash
#
# Remove generated files that Hugo recreates on the next `hugo` / `hugo server`
# run (or `pnpm build` / `pnpm dev`). Everything removed here is gitignored.
#
# Kept on purpose:
#   node_modules/   needs `pnpm install` to restore, not regenerated by Hugo
#   Hugo module cache (outside the repo; clear with `hugo mod clean` if needed)
#
# Usage: scripts/clean.sh [-n]
#   -n  dry run: list what would be removed without deleting anything

set -euo pipefail

dry_run=false
if [[ "${1:-}" == "-n" ]]; then
  dry_run=true
elif [[ $# -gt 0 ]]; then
  echo "Usage: $0 [-n]" >&2
  exit 1
fi

# Run from the repository root regardless of the caller's working directory.
cd "$(dirname "$0")/.."

targets=(
  public            # built site (`hugo` output, plus Pagefind index)
  resources         # processed images and CSS cache
  hugo_stats.json   # class/tag stats (build.writeStats) used by Tailwind
  .hugo_build.lock  # build lock file
  assets/jsconfig.json  # JS path mappings Hugo writes for editors
  pagefind          # Pagefind search index, if built outside public/
  static/pagefind
)

remove() {
  if $dry_run; then
    echo "would remove: $1"
  else
    rm -rf -- "$1"
    echo "removed: $1"
  fi
}

for target in "${targets[@]}"; do
  if [[ -e "$target" ]]; then
    remove "$target"
  fi
done

# macOS Finder metadata (not Hugo output, but never needed in the repo).
while IFS= read -r -d '' ds_store; do
  remove "${ds_store#./}"
done < <(find . -name .DS_Store -not -path './node_modules/*' -not -path './.git/*' -print0)
